#ifndef CALIBRATION_SERVICE_IDL
#define CALIBRATION_SERVICE_IDL

#include "InterfaceDataTypes.idl"

module ImageCalibService
{
  typedef sequence<RTC::CameraImage> ImageList;
  interface CalibrationService 
  {
    void setImageNumber(in short num);
    short getImageNumber();
    RTC::CameraImage captureCalibImage(in short num);
    RTC::CameraImage getCalibImage(in short num);
    ImageList getCalibImages();
    boolean removeCalibImage(in short num);
    RTC::CameraInfo getCalibParameter();
  };
};

#endif	/* CALIBRATION_SERVICE_IDL */

